export const data = [{
  "id": 1,
  "Date_printed": "11/15/2022",
  "Company_file_number": 8405782,
  "Company_name": "Reilly-Strosin",
  "Staff_name": "Fremont Hruska",
  "Total_earned_income": "#2.31",
  "Relief": "#2.45",
  "Taxable_income": "#0.81",
  "Tax_payable": "#8.17",
  "Tax_already_deducted": "#1.64",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 2,
  "Date_printed": "2/15/2023",
  "Company_file_number": 6441406,
  "Company_name": "Daugherty Inc",
  "Staff_name": "Hildagarde Boerderman",
  "Total_earned_income": "#4.40",
  "Relief": "#3.49",
  "Taxable_income": "#2.23",
  "Tax_payable": "#4.72",
  "Tax_already_deducted": "#8.75",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 3,
  "Date_printed": "5/15/2023",
  "Company_file_number": 8393352,
  "Company_name": "McGlynn, Lesch and Macejkovic",
  "Staff_name": "Hayden Crew",
  "Total_earned_income": "#8.58",
  "Relief": "#4.48",
  "Taxable_income": "#7.93",
  "Tax_payable": "#5.36",
  "Tax_already_deducted": "#3.03",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 4,
  "Date_printed": "2/24/2023",
  "Company_file_number": 2691911,
  "Company_name": "Bartell, Bode and Carter",
  "Staff_name": "Pearla Grzeszczak",
  "Total_earned_income": "#6.57",
  "Relief": "#6.57",
  "Taxable_income": "#0.97",
  "Tax_payable": "#8.12",
  "Tax_already_deducted": "#5.58",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 5,
  "Date_printed": "11/24/2022",
  "Company_file_number": 2511473,
  "Company_name": "Stokes and Sons",
  "Staff_name": "Paddie Stillgoe",
  "Total_earned_income": "#1.31",
  "Relief": "#4.89",
  "Taxable_income": "#8.71",
  "Tax_payable": "#1.57",
  "Tax_already_deducted": "#7.52",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 6,
  "Date_printed": "1/27/2023",
  "Company_file_number": 4823717,
  "Company_name": "Collier, Langosh and Marvin",
  "Staff_name": "Astra Vurley",
  "Total_earned_income": "#6.71",
  "Relief": "#5.30",
  "Taxable_income": "#7.23",
  "Tax_payable": "#1.89",
  "Tax_already_deducted": "#8.81",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 7,
  "Date_printed": "7/15/2022",
  "Company_file_number": 8293765,
  "Company_name": "Hayes-Mante",
  "Staff_name": "Adriana Cranham",
  "Total_earned_income": "#5.73",
  "Relief": "#2.61",
  "Taxable_income": "#0.91",
  "Tax_payable": "#8.04",
  "Tax_already_deducted": "#8.38",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 8,
  "Date_printed": "3/17/2023",
  "Company_file_number": 3266862,
  "Company_name": "Lesch, Moen and DuBuque",
  "Staff_name": "Joellyn Lightoller",
  "Total_earned_income": "#6.65",
  "Relief": "#3.46",
  "Taxable_income": "#9.60",
  "Tax_payable": "#5.72",
  "Tax_already_deducted": "#0.14",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 9,
  "Date_printed": "12/16/2022",
  "Company_file_number": 1271578,
  "Company_name": "Bashirian-Wolff",
  "Staff_name": "Bari Buchett",
  "Total_earned_income": "#8.90",
  "Relief": "#2.20",
  "Taxable_income": "#5.90",
  "Tax_payable": "#3.72",
  "Tax_already_deducted": "#3.18",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 10,
  "Date_printed": "8/31/2022",
  "Company_file_number": 1966480,
  "Company_name": "Barton-Hammes",
  "Staff_name": "Shawna Rastrick",
  "Total_earned_income": "#7.06",
  "Relief": "#2.08",
  "Taxable_income": "#9.82",
  "Tax_payable": "#2.96",
  "Tax_already_deducted": "#3.88",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 11,
  "Date_printed": "2/24/2023",
  "Company_file_number": 2653336,
  "Company_name": "Schiller-Prohaska",
  "Staff_name": "Gertruda Glison",
  "Total_earned_income": "#0.73",
  "Relief": "#7.17",
  "Taxable_income": "#8.94",
  "Tax_payable": "#9.36",
  "Tax_already_deducted": "#8.56",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 12,
  "Date_printed": "2/3/2023",
  "Company_file_number": 5876825,
  "Company_name": "Glover and Sons",
  "Staff_name": "Darla Hanby",
  "Total_earned_income": "#0.24",
  "Relief": "#1.87",
  "Taxable_income": "#9.27",
  "Tax_payable": "#8.56",
  "Tax_already_deducted": "#5.96",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 13,
  "Date_printed": "8/10/2022",
  "Company_file_number": 2594629,
  "Company_name": "Koelpin-Green",
  "Staff_name": "Minnie Moggan",
  "Total_earned_income": "#0.45",
  "Relief": "#0.95",
  "Taxable_income": "#4.09",
  "Tax_payable": "#1.39",
  "Tax_already_deducted": "#2.01",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 14,
  "Date_printed": "12/7/2022",
  "Company_file_number": 5276280,
  "Company_name": "Kreiger and Sons",
  "Staff_name": "Verney Arkley",
  "Total_earned_income": "#0.71",
  "Relief": "#7.81",
  "Taxable_income": "#7.28",
  "Tax_payable": "#5.00",
  "Tax_already_deducted": "#4.74",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 15,
  "Date_printed": "9/11/2022",
  "Company_file_number": 4735927,
  "Company_name": "Hermiston-Heathcote",
  "Staff_name": "Charlie Hankinson",
  "Total_earned_income": "#5.35",
  "Relief": "#9.27",
  "Taxable_income": "#7.04",
  "Tax_payable": "#7.54",
  "Tax_already_deducted": "#4.91",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 16,
  "Date_printed": "10/9/2022",
  "Company_file_number": 3988200,
  "Company_name": "Kovacek, Sawayn and Botsford",
  "Staff_name": "Iain Jiroutka",
  "Total_earned_income": "#9.97",
  "Relief": "#3.03",
  "Taxable_income": "#5.61",
  "Tax_payable": "#6.65",
  "Tax_already_deducted": "#4.72",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 17,
  "Date_printed": "8/28/2022",
  "Company_file_number": 7264996,
  "Company_name": "Metz, Bechtelar and Rogahn",
  "Staff_name": "Bobby Halshaw",
  "Total_earned_income": "#4.62",
  "Relief": "#3.13",
  "Taxable_income": "#5.81",
  "Tax_payable": "#6.82",
  "Tax_already_deducted": "#9.91",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 18,
  "Date_printed": "11/17/2022",
  "Company_file_number": 4412957,
  "Company_name": "Powlowski-Torphy",
  "Staff_name": "Dicky Hancock",
  "Total_earned_income": "#3.55",
  "Relief": "#3.12",
  "Taxable_income": "#7.28",
  "Tax_payable": "#3.51",
  "Tax_already_deducted": "#3.31",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 19,
  "Date_printed": "7/4/2023",
  "Company_file_number": 6977879,
  "Company_name": "Rath-Goldner",
  "Staff_name": "Carmel Blenkharn",
  "Total_earned_income": "#3.68",
  "Relief": "#6.23",
  "Taxable_income": "#6.59",
  "Tax_payable": "#3.12",
  "Tax_already_deducted": "#3.97",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 20,
  "Date_printed": "6/14/2023",
  "Company_file_number": 6054010,
  "Company_name": "Hayes-Will",
  "Staff_name": "Sarge Tace",
  "Total_earned_income": "#3.09",
  "Relief": "#5.04",
  "Taxable_income": "#5.94",
  "Tax_payable": "#1.55",
  "Tax_already_deducted": "#7.75",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 21,
  "Date_printed": "6/11/2023",
  "Company_file_number": 9814496,
  "Company_name": "Kerluke, Buckridge and Hauck",
  "Staff_name": "Linn Chansonnau",
  "Total_earned_income": "#3.27",
  "Relief": "#4.59",
  "Taxable_income": "#8.33",
  "Tax_payable": "#7.99",
  "Tax_already_deducted": "#4.31",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 22,
  "Date_printed": "3/20/2023",
  "Company_file_number": 9231216,
  "Company_name": "Treutel, Beatty and Hodkiewicz",
  "Staff_name": "Alison McPaik",
  "Total_earned_income": "#7.57",
  "Relief": "#2.94",
  "Taxable_income": "#0.01",
  "Tax_payable": "#4.79",
  "Tax_already_deducted": "#1.10",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 23,
  "Date_printed": "2/8/2023",
  "Company_file_number": 1612998,
  "Company_name": "Armstrong, Deckow and Lockman",
  "Staff_name": "Dulcy Lamblot",
  "Total_earned_income": "#2.03",
  "Relief": "#7.97",
  "Taxable_income": "#3.39",
  "Tax_payable": "#5.80",
  "Tax_already_deducted": "#5.34",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 24,
  "Date_printed": "7/7/2022",
  "Company_file_number": 3825401,
  "Company_name": "Ziemann-Conn",
  "Staff_name": "Dalton Sant",
  "Total_earned_income": "#1.86",
  "Relief": "#1.05",
  "Taxable_income": "#4.04",
  "Tax_payable": "#5.41",
  "Tax_already_deducted": "#4.95",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 25,
  "Date_printed": "2/13/2023",
  "Company_file_number": 3029592,
  "Company_name": "Cole, Cassin and Yundt",
  "Staff_name": "Mervin Brewood",
  "Total_earned_income": "#4.07",
  "Relief": "#0.82",
  "Taxable_income": "#1.71",
  "Tax_payable": "#7.31",
  "Tax_already_deducted": "#6.27",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 26,
  "Date_printed": "8/18/2022",
  "Company_file_number": 7231173,
  "Company_name": "Hintz, Lowe and Hayes",
  "Staff_name": "Kaitlin Maunder",
  "Total_earned_income": "#4.89",
  "Relief": "#9.40",
  "Taxable_income": "#9.90",
  "Tax_payable": "#3.35",
  "Tax_already_deducted": "#9.53",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 27,
  "Date_printed": "6/4/2023",
  "Company_file_number": 9572695,
  "Company_name": "Rowe, Miller and Rowe",
  "Staff_name": "Vikki Angrove",
  "Total_earned_income": "#5.26",
  "Relief": "#8.77",
  "Taxable_income": "#1.94",
  "Tax_payable": "#5.82",
  "Tax_already_deducted": "#4.69",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 28,
  "Date_printed": "11/23/2022",
  "Company_file_number": 5633593,
  "Company_name": "Turner, Wyman and Boyer",
  "Staff_name": "Maureene Mackleden",
  "Total_earned_income": "#3.35",
  "Relief": "#4.65",
  "Taxable_income": "#1.13",
  "Tax_payable": "#6.45",
  "Tax_already_deducted": "#4.73",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 29,
  "Date_printed": "3/9/2023",
  "Company_file_number": 1397940,
  "Company_name": "Kirlin-Kihn",
  "Staff_name": "Lissi Sayburn",
  "Total_earned_income": "#9.14",
  "Relief": "#4.53",
  "Taxable_income": "#7.39",
  "Tax_payable": "#1.64",
  "Tax_already_deducted": "#4.93",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 30,
  "Date_printed": "9/26/2022",
  "Company_file_number": 9881297,
  "Company_name": "Boyle Inc",
  "Staff_name": "Engracia Somerbell",
  "Total_earned_income": "#1.37",
  "Relief": "#4.92",
  "Taxable_income": "#1.22",
  "Tax_payable": "#9.67",
  "Tax_already_deducted": "#6.77",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 31,
  "Date_printed": "11/26/2022",
  "Company_file_number": 2646939,
  "Company_name": "Little-O'Hara",
  "Staff_name": "Lulita Summerell",
  "Total_earned_income": "#6.62",
  "Relief": "#4.48",
  "Taxable_income": "#4.87",
  "Tax_payable": "#0.67",
  "Tax_already_deducted": "#0.43",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 32,
  "Date_printed": "4/16/2023",
  "Company_file_number": 1690801,
  "Company_name": "Breitenberg and Sons",
  "Staff_name": "Wynny Savage",
  "Total_earned_income": "#0.48",
  "Relief": "#5.74",
  "Taxable_income": "#5.57",
  "Tax_payable": "#9.77",
  "Tax_already_deducted": "#1.50",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 33,
  "Date_printed": "10/27/2022",
  "Company_file_number": 4793527,
  "Company_name": "Hammes-Schaefer",
  "Staff_name": "Doria Densie",
  "Total_earned_income": "#3.68",
  "Relief": "#2.98",
  "Taxable_income": "#3.60",
  "Tax_payable": "#9.18",
  "Tax_already_deducted": "#1.61",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 34,
  "Date_printed": "5/7/2023",
  "Company_file_number": 3883824,
  "Company_name": "Morar-Osinski",
  "Staff_name": "Barny Korpolak",
  "Total_earned_income": "#6.15",
  "Relief": "#4.40",
  "Taxable_income": "#4.77",
  "Tax_payable": "#0.87",
  "Tax_already_deducted": "#2.25",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 35,
  "Date_printed": "8/16/2022",
  "Company_file_number": 9938690,
  "Company_name": "Rolfson, Brakus and Toy",
  "Staff_name": "Lilith Burris",
  "Total_earned_income": "#8.39",
  "Relief": "#8.94",
  "Taxable_income": "#5.01",
  "Tax_payable": "#3.81",
  "Tax_already_deducted": "#7.00",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 36,
  "Date_printed": "4/17/2023",
  "Company_file_number": 8386490,
  "Company_name": "Mills-Mraz",
  "Staff_name": "Vincenz Bowich",
  "Total_earned_income": "#8.66",
  "Relief": "#4.50",
  "Taxable_income": "#7.67",
  "Tax_payable": "#3.52",
  "Tax_already_deducted": "#3.49",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 37,
  "Date_printed": "8/4/2022",
  "Company_file_number": 8680582,
  "Company_name": "Erdman, Schinner and DuBuque",
  "Staff_name": "Matilde Dreschler",
  "Total_earned_income": "#6.13",
  "Relief": "#4.29",
  "Taxable_income": "#9.54",
  "Tax_payable": "#5.44",
  "Tax_already_deducted": "#0.55",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 38,
  "Date_printed": "7/27/2022",
  "Company_file_number": 6473291,
  "Company_name": "Stiedemann, Kautzer and Lang",
  "Staff_name": "Nelle Attwood",
  "Total_earned_income": "#2.55",
  "Relief": "#7.03",
  "Taxable_income": "#7.17",
  "Tax_payable": "#9.49",
  "Tax_already_deducted": "#2.43",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 39,
  "Date_printed": "8/10/2022",
  "Company_file_number": 8935878,
  "Company_name": "Mohr Inc",
  "Staff_name": "Saxon Jankovic",
  "Total_earned_income": "#1.06",
  "Relief": "#7.14",
  "Taxable_income": "#3.20",
  "Tax_payable": "#7.32",
  "Tax_already_deducted": "#1.69",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 40,
  "Date_printed": "10/16/2022",
  "Company_file_number": 8632060,
  "Company_name": "Schimmel, Swift and Kassulke",
  "Staff_name": "Nelly Martinello",
  "Total_earned_income": "#2.89",
  "Relief": "#2.78",
  "Taxable_income": "#8.33",
  "Tax_payable": "#7.01",
  "Tax_already_deducted": "#6.80",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 41,
  "Date_printed": "12/13/2022",
  "Company_file_number": 7312324,
  "Company_name": "Crooks Inc",
  "Staff_name": "Arda Faircliff",
  "Total_earned_income": "#4.09",
  "Relief": "#8.52",
  "Taxable_income": "#4.47",
  "Tax_payable": "#9.85",
  "Tax_already_deducted": "#8.03",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 42,
  "Date_printed": "11/14/2022",
  "Company_file_number": 2743270,
  "Company_name": "Mraz, Hartmann and Becker",
  "Staff_name": "Ly Andino",
  "Total_earned_income": "#0.15",
  "Relief": "#1.19",
  "Taxable_income": "#7.21",
  "Tax_payable": "#8.98",
  "Tax_already_deducted": "#4.71",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 43,
  "Date_printed": "7/25/2022",
  "Company_file_number": 3621138,
  "Company_name": "Rowe-Kertzmann",
  "Staff_name": "Aloisia Giorgetti",
  "Total_earned_income": "#2.18",
  "Relief": "#1.55",
  "Taxable_income": "#8.24",
  "Tax_payable": "#8.30",
  "Tax_already_deducted": "#4.06",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 44,
  "Date_printed": "10/24/2022",
  "Company_file_number": 5206553,
  "Company_name": "Collins Inc",
  "Staff_name": "Maisie Rumsey",
  "Total_earned_income": "#2.84",
  "Relief": "#1.73",
  "Taxable_income": "#0.03",
  "Tax_payable": "#2.32",
  "Tax_already_deducted": "#5.97",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 45,
  "Date_printed": "5/28/2023",
  "Company_file_number": 7919473,
  "Company_name": "Bernhard Inc",
  "Staff_name": "Bab Figgess",
  "Total_earned_income": "#9.57",
  "Relief": "#2.40",
  "Taxable_income": "#7.99",
  "Tax_payable": "#6.49",
  "Tax_already_deducted": "#6.97",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 46,
  "Date_printed": "8/31/2022",
  "Company_file_number": 7251592,
  "Company_name": "Muller-Sauer",
  "Staff_name": "Murial Coonan",
  "Total_earned_income": "#5.47",
  "Relief": "#2.38",
  "Taxable_income": "#1.29",
  "Tax_payable": "#8.27",
  "Tax_already_deducted": "#6.95",
  "Underpayment_Overpayment": "Underpayment"
}, {
  "id": 47,
  "Date_printed": "3/1/2023",
  "Company_file_number": 6406818,
  "Company_name": "Trantow-Hartmann",
  "Staff_name": "Orelie Genicke",
  "Total_earned_income": "#4.70",
  "Relief": "#4.50",
  "Taxable_income": "#4.89",
  "Tax_payable": "#4.48",
  "Tax_already_deducted": "#4.83",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 48,
  "Date_printed": "5/21/2023",
  "Company_file_number": 2687733,
  "Company_name": "Beier and Sons",
  "Staff_name": "Sari Bakhrushkin",
  "Total_earned_income": "#5.93",
  "Relief": "#8.42",
  "Taxable_income": "#0.27",
  "Tax_payable": "#1.66",
  "Tax_already_deducted": "#1.24",
  "Underpayment_Overpayment": "Overpayment"
}, {
  "id": 49,
  "Date_printed": "1/13/2023",
  "Company_file_number": 2857103,
  "Company_name": "Kozey-Schuppe",
  "Staff_name": "Jaymie Henryson",
  "Total_earned_income": "#6.90",
  "Relief": "#9.66",
  "Taxable_income": "#7.12",
  "Tax_payable": "#8.79",
  "Tax_already_deducted": "#0.71",
  "Underpayment_Overpayment": "Overpayment"
}
]