export const data3 = [
  {
    operatorname: "Duke Hasker",
    totalmonthlyremittancesmade: "#363.06",
    totalremittancesfortheyear: "#362.26",
    outstandingliability: "#263.20",
  },
  {
    operatorname: "Analise Scanlon",
    totalmonthlyremittancesmade: "#331.91",
    totalremittancesfortheyear: "#703.41",
    outstandingliability: "#319.60",
  },
  {
    operatorname: "Almire Lindfors",
    totalmonthlyremittancesmade: "#214.55",
    totalremittancesfortheyear: "#500.62",
    outstandingliability: "#441.71",
  },
  {
    operatorname: "Angel Deppe",
    totalmonthlyremittancesmade: "#352.68",
    totalremittancesfortheyear: "#344.87",
    outstandingliability: "#511.66",
  },
  {
    operatorname: "Christian Brader",
    totalmonthlyremittancesmade: "#265.34",
    totalremittancesfortheyear: "#484.87",
    outstandingliability: "#544.15",
  },
  {
    operatorname: "Hartley Vankov",
    totalmonthlyremittancesmade: "#218.77",
    totalremittancesfortheyear: "#623.78",
    outstandingliability: "#311.50",
  },
  {
    operatorname: "Maurise Wilmut",
    totalmonthlyremittancesmade: "#255.11",
    totalremittancesfortheyear: "#937.46",
    outstandingliability: "#322.37",
  },
  {
    operatorname: "Courtney Jakubovics",
    totalmonthlyremittancesmade: "#278.23",
    totalremittancesfortheyear: "#809.72",
    outstandingliability: "#424.92",
  },
  {
    operatorname: "Dannie Clawsley",
    totalmonthlyremittancesmade: "#271.18",
    totalremittancesfortheyear: "#838.31",
    outstandingliability: "#507.75",
  },
  {
    operatorname: "Burr Stawell",
    totalmonthlyremittancesmade: "#363.48",
    totalremittancesfortheyear: "#871.89",
    outstandingliability: "#350.10",
  },
  {
    operatorname: "Bridie Perrett",
    totalmonthlyremittancesmade: "#317.85",
    totalremittancesfortheyear: "#758.75",
    outstandingliability: "#314.56",
  },
  {
    operatorname: "Siward Moggach",
    totalmonthlyremittancesmade: "#290.03",
    totalremittancesfortheyear: "#926.13",
    outstandingliability: "#287.55",
  },
  {
    operatorname: "Alidia Ferreri",
    totalmonthlyremittancesmade: "#212.37",
    totalremittancesfortheyear: "#869.38",
    outstandingliability: "#425.89",
  },
  {
    operatorname: "Sondra Pipping",
    totalmonthlyremittancesmade: "#307.19",
    totalremittancesfortheyear: "#631.40",
    outstandingliability: "#492.02",
  },
  {
    operatorname: "Kris Hanhart",
    totalmonthlyremittancesmade: "#359.38",
    totalremittancesfortheyear: "#751.34",
    outstandingliability: "#449.78",
  },
  {
    operatorname: "Yuri Janout",
    totalmonthlyremittancesmade: "#321.06",
    totalremittancesfortheyear: "#764.99",
    outstandingliability: "#389.62",
  },
  {
    operatorname: "Caty Creane",
    totalmonthlyremittancesmade: "#200.42",
    totalremittancesfortheyear: "#831.86",
    outstandingliability: "#288.09",
  },
  {
    operatorname: "Ryun Gronowe",
    totalmonthlyremittancesmade: "#200.09",
    totalremittancesfortheyear: "#386.30",
    outstandingliability: "#442.09",
  },
  {
    operatorname: "Daron Wingeatt",
    totalmonthlyremittancesmade: "#361.11",
    totalremittancesfortheyear: "#868.49",
    outstandingliability: "#451.68",
  },
  {
    operatorname: "Barton Pidgeley",
    totalmonthlyremittancesmade: "#274.81",
    totalremittancesfortheyear: "#806.85",
    outstandingliability: "#331.68",
  },
  {
    operatorname: "Cynde Stigger",
    totalmonthlyremittancesmade: "#307.68",
    totalremittancesfortheyear: "#330.33",
    outstandingliability: "#367.54",
  },
  {
    operatorname: "Neil Hannah",
    totalmonthlyremittancesmade: "#203.88",
    totalremittancesfortheyear: "#671.39",
    outstandingliability: "#436.89",
  },
  {
    operatorname: "Elmore Blague",
    totalmonthlyremittancesmade: "#315.33",
    totalremittancesfortheyear: "#398.88",
    outstandingliability: "#491.84",
  },
  {
    operatorname: "Jordan Moogan",
    totalmonthlyremittancesmade: "#376.93",
    totalremittancesfortheyear: "#628.30",
    outstandingliability: "#401.05",
  },
  {
    operatorname: "Harlin Tennewell",
    totalmonthlyremittancesmade: "#393.16",
    totalremittancesfortheyear: "#973.06",
    outstandingliability: "#350.57",
  },
  {
    operatorname: "Martina Dimont",
    totalmonthlyremittancesmade: "#361.87",
    totalremittancesfortheyear: "#916.93",
    outstandingliability: "#302.59",
  },
  {
    operatorname: "Hadlee Daintith",
    totalmonthlyremittancesmade: "#340.22",
    totalremittancesfortheyear: "#315.86",
    outstandingliability: "#469.03",
  },
  {
    operatorname: "Danielle Joberne",
    totalmonthlyremittancesmade: "#212.91",
    totalremittancesfortheyear: "#376.19",
    outstandingliability: "#460.23",
  },
  {
    operatorname: "Hazlett Nickels",
    totalmonthlyremittancesmade: "#388.41",
    totalremittancesfortheyear: "#339.63",
    outstandingliability: "#476.59",
  },
  {
    operatorname: "Helli Tremmel",
    totalmonthlyremittancesmade: "#311.94",
    totalremittancesfortheyear: "#816.00",
    outstandingliability: "#397.10",
  },
  {
    operatorname: "Angeli Rodbourne",
    totalmonthlyremittancesmade: "#241.53",
    totalremittancesfortheyear: "#816.62",
    outstandingliability: "#435.32",
  },
  {
    operatorname: "Roderich Yglesias",
    totalmonthlyremittancesmade: "#310.28",
    totalremittancesfortheyear: "#508.06",
    outstandingliability: "#272.15",
  },
  {
    operatorname: "Goober Loffel",
    totalmonthlyremittancesmade: "#233.39",
    totalremittancesfortheyear: "#605.67",
    outstandingliability: "#328.38",
  },
  {
    operatorname: "Lenard Krebs",
    totalmonthlyremittancesmade: "#392.48",
    totalremittancesfortheyear: "#994.23",
    outstandingliability: "#521.06",
  },
  {
    operatorname: "Robbyn Shaxby",
    totalmonthlyremittancesmade: "#336.67",
    totalremittancesfortheyear: "#390.22",
    outstandingliability: "#348.02",
  },
  {
    operatorname: "Lilli Pallasch",
    totalmonthlyremittancesmade: "#325.94",
    totalremittancesfortheyear: "#634.88",
    outstandingliability: "#405.34",
  },
  {
    operatorname: "Arney Glencrosche",
    totalmonthlyremittancesmade: "#333.94",
    totalremittancesfortheyear: "#686.06",
    outstandingliability: "#293.61",
  },
  {
    operatorname: "Chip Mardell",
    totalmonthlyremittancesmade: "#239.08",
    totalremittancesfortheyear: "#919.45",
    outstandingliability: "#540.21",
  },
  {
    operatorname: "Lutero Manicomb",
    totalmonthlyremittancesmade: "#226.78",
    totalremittancesfortheyear: "#819.66",
    outstandingliability: "#496.41",
  },
  {
    operatorname: "Horton Rainger",
    totalmonthlyremittancesmade: "#396.02",
    totalremittancesfortheyear: "#389.77",
    outstandingliability: "#250.96",
  },
  {
    operatorname: "Ilyse Obington",
    totalmonthlyremittancesmade: "#328.48",
    totalremittancesfortheyear: "#512.65",
    outstandingliability: "#327.13",
  },
  {
    operatorname: "Erick Elliker",
    totalmonthlyremittancesmade: "#274.11",
    totalremittancesfortheyear: "#780.27",
    outstandingliability: "#283.43",
  },
  {
    operatorname: "Derrick Pepperell",
    totalmonthlyremittancesmade: "#377.33",
    totalremittancesfortheyear: "#507.89",
    outstandingliability: "#325.71",
  },
  {
    operatorname: "Ibby Chitter",
    totalmonthlyremittancesmade: "#377.52",
    totalremittancesfortheyear: "#903.41",
    outstandingliability: "#348.64",
  },
  {
    operatorname: "Janeva Ruffli",
    totalmonthlyremittancesmade: "#203.38",
    totalremittancesfortheyear: "#880.64",
    outstandingliability: "#507.30",
  },
  {
    operatorname: "Travers Stenner",
    totalmonthlyremittancesmade: "#233.92",
    totalremittancesfortheyear: "#441.97",
    outstandingliability: "#283.63",
  },
  {
    operatorname: "Janeta Noore",
    totalmonthlyremittancesmade: "#323.72",
    totalremittancesfortheyear: "#672.68",
    outstandingliability: "#260.57",
  },
  {
    operatorname: "Reinaldos Stares",
    totalmonthlyremittancesmade: "#250.11",
    totalremittancesfortheyear: "#798.14",
    outstandingliability: "#287.23",
  },
  {
    operatorname: "Angel Human",
    totalmonthlyremittancesmade: "#209.25",
    totalremittancesfortheyear: "#910.34",
    outstandingliability: "#502.74",
  },
  {
    operatorname: "Jenilee Aldred",
    totalmonthlyremittancesmade: "#244.43",
    totalremittancesfortheyear: "#457.27",
    outstandingliability: "#423.43",
  },
];
